version: "3.7"

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    container_name: redis


  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=ketabak_db
      - POSTGRES_USER=ketabak_user
      - POSTGRES_PASSWORD=ali0013khani
    volumes:
      - ~/data/:/var/lib/postgresql/data
    env_file:
      - .env
    container_name: db


  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    container_name: smtp4dev
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev


  ketabak:
    depends_on:
      - db
      - smtp4dev
      - redis
    container_name: ketabak
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

  testing:
    depends_on:
      - db
      - ketabak
      - redis
    container_name: testing
    command: python manage.py test 

    volumes:
      - type: bind
        source: .
        target: /app

    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile

  worker:
    container_name: worker
    build: .
    command: >
      celery -A core worker -l INFO
      && celery -A core beat -l INFO
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - redis
      - db
      - ketabak



volumes:
  smtp4dev-data:
