# Generated by Django 4.2.7 on 2023-11-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(max_length=11)),
                ("address", models.TextField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("validity_ar", models.DateTimeField()),
                ("books", models.ManyToManyField(to="books.book")),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "Orders",
            },
        ),
    ]
