# Generated by Django 4.2.7 on 2023-12-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BorrowedBooks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("validity_at", models.DateTimeField(blank=True, null=True)),
                ("books", models.ManyToManyField(to="books.book")),
            ],
            options={
                "verbose_name": "Borrowed Book",
                "verbose_name_plural": "Borrowed Books",
                "db_table": "BorrowedBooks",
            },
        ),
    ]
