# Generated by Django 4.2.7 on 2023-11-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BorrowedBooks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(max_length=11)),
                ("address", models.TextField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("validity_at", models.DateTimeField()),
                ("books", models.ManyToManyField(to="books.book")),
            ],
            options={
                "verbose_name": "Borrowed Book",
                "verbose_name_plural": "Borrowed Books",
                "db_table": "BorrowedBooks",
            },
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
