# Generated by Django 4.2.7 on 2023-11-18 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0003_alter_borrowedbooks_validity_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowedbooks",
            name="customer_email",
        ),
        migrations.RemoveField(
            model_name="borrowedbooks",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="borrowedbooks",
            name="customer_phone",
        ),
        migrations.AddField(
            model_name="borrowedbooks",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
